node_js-steps: &node_js-steps
  language: node_js
  script: make travis
  after_script: make report

python-steps: &python-steps
  language: python
  install: pip install flake8
  script:
    # stop the build if there are Python syntax errors or undefined names
    - flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
    - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

matrix:
  include:
    - node_js: "8"
      <<: *node_js-steps
    - node_js: "10"
      <<: *node_js-steps
    - node_js: "node"  # current version of Node.js on Travis CI
      <<: *node_js-steps
    - python: "2.7"
      <<: *python-steps
    - python: "3.8"
      <<: *python-steps
